export const stockData = [
  {
    symbol: "AMZN",
    latestPrice: 200,
    change: -1,
    changePercent: -0.25,
    riskLevel: "Low Risk",
  },
  {
    symbol: "TSLA",
    latestPrice: 200,
    change: 1,
    changePercent: -0.25,
    riskLevel: "Low Risk",
  },
  {
    symbol: "AAPL",
    latestPrice: 100,
    change: 1,
    changePercent: 0.25,
    riskLevel: "High Risk",
  },
  {
    symbol: "GOOGL",
    latestPrice: 300,
    change: 0,
    changePercent: 0,
    riskLevel: "Medium Risk",
  },
  {
    symbol: "MSFT",
    latestPrice: 150,
    change: -2,
    changePercent: -0.75,
    riskLevel: "Low Risk",
  },
  {
    symbol: "FB",
    latestPrice: 250,
    change: 0,
    changePercent: 0,
    riskLevel: "High Risk",
  },
  {
    symbol: "NFLX",
    latestPrice: 100,
    change: 1,
    changePercent: 0.25,
    riskLevel: "Medium Risk",
  },
  {
    symbol: "NVDA",
    latestPrice: 200,
    change: -1,
    changePercent: -0.25,
    riskLevel: "Low Risk",
  },
  {
    symbol: "PYPL",
    latestPrice: 200,
    change: 1,
    changePercent: -0.25,
    riskLevel: "Low Risk",
  },
  {
    symbol: "INTC",
    latestPrice: 100,
    change: 1,
    changePercent: 0.25,
    riskLevel: "High Risk",
  },
  {
    symbol: "ADBE",
    latestPrice: 300,
    change: 0,
    changePercent: 0,
    riskLevel: "Medium Risk",
  },
  {
    symbol: "CSCO",
    latestPrice: 150,
    change: -2,
    changePercent: -0.75,
    riskLevel: "Low Risk",
  },
  {
    symbol: "CMCSA",
    latestPrice: 250,
    change: 0,
    changePercent: 0,
    riskLevel: "High Risk",
  },
  {
    symbol: "PEP",
    latestPrice: 100,
    change: 1,
    changePercent: 0.25,
    riskLevel: "Medium Risk",
  },
  {
    symbol: "AVGO",
    latestPrice: 200,
    change: -1,
    changePercent: -0.25,
    riskLevel: "Low Risk",
  },
  {
    symbol: "QCOM",
    latestPrice: 200,
    change: 1,
    changePercent: -0.25,
    riskLevel: "Low Risk",
  },
  {
    symbol: "TXN",
    latestPrice: 100,
    change: 1,
    changePercent: 0.25,
    riskLevel: "High Risk",
  },
  {
    symbol: "COST",
    latestPrice: 300,
    change: 0,
    changePercent: 0,
    riskLevel: "Medium Risk",
  },
];
